#!/bin/sh -e

export PERL5LIB=/home/minivend/datafilter
cd ~/matstock/stocks
for file in *.txt; do 
	echo "Processing file $file"
	echo "---------------------"
	echo ""
	# derive customerid from input file
	tmpfile=`tempfile`
	cut -f 2 "$file" | sed -ne '/[0-9A-Za-z]/p' | uniq > $tmpfile
	lines=`wc -l < $tmpfile`

 	if [ $lines -gt 1 ]; then
		echo "No unique customerid, skipping input file"
 	else
		customerid=`cat $tmpfile`
		echo "Customerid $customerid"
		~/datafilter/examples/allstocks "$file" "$customerid"
	fi
	rm "$tmpfile"
	echo ""
done

