#! /usr/bin/env perl

# datafilter - command line tool for DataFilter suite

# Copyright (C) 2006,2007,2009,2010 Stefan Hornburg (Racke) <racke@linuxia.de>

# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2, or (at your option) any
# later version.

# This file is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this file; see the file COPYING.  If not, write to the Free
# Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.

use strict;
use warnings;

use Getopt::Long;

use DataFilter;

# process commandline parameters
my %opts;
my $whandler = $SIG{__WARN__};
$SIG{__WARN__} = sub {print STDERR "$0: @_";};
unless (GetOptions (\%opts, 'show-columns', 'show-tables',
					'skip-before=s', 'rowspan=i',
					'config-file|c=s',
					'allow-loose-quotes',
					'encoding-in=s', 'encoding-out=s',
					'header-row=i',
					'match=s',
					'noheader')) {
    exit 1;
}
$SIG{__WARN__} = $whandler;


#
my $df = new DataFilter;
my ($input, $output, $type, $record);
my (%input_parms, $parm_name, $input_spec, $output_spec);

if ($opts{'config-file'}) {
	$df->configure(type => 'AppConfig', file => $opts{'config-file'});
	$input = $df->source();
	$output = $df->target();
}
else {
	# sanity check
	unless (@ARGV) {
		die "$0: missing parameters\n";
	}

	($input_spec, $output_spec) = @ARGV;

	%input_parms = (name => $input_spec,
					noheader => $opts{noheader},
					rowspan => $opts{rowspan},
					header_row => $opts{'header-row'},
					skip_before => $opts{'skip-before'});

	for (qw/allow-loose-quotes encoding-in encoding-out/) {
		if (exists $opts{$_}) {
			$parm_name = $_;
			$parm_name =~ s/-/_/g;
			
			$input_parms{$parm_name} = $opts{$_};
		}
	}
	
	$input = $df->source(%input_parms);
}


if ($opts{'show-tables'}) {
	for ($input->tables()) {
		print "$_\n";
	}
}

if ($opts{'show-columns'}) {
	for ($input->columns()) {
		print "$_\n";
	}
}

if (defined $output_spec) {
	if ($output_spec =~ s/^(xls|csv|tab)://i
		|| $output_spec =~ m/\.(xls|csv|tab)$/i) {
		$output = $df->target(type => uc($1),
							  name => $output_spec,
							  columns => [$input->columns()]);
	}
}

if ($output) {
	while ($record = $input->enum_records()) {
		if (defined $opts{match}
			&& $opts{match} =~ /^(\w+)([=~])(.*)$/) {
			my ($field, $op, $value) = ($1, $2, $3);										unless ($record->{$field} eq $value) {
				next;
			}
		}
		
		$output->add_record('', $record);
	}
}

